services:
  web:
    build: .
    container_name: ultimate-website-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - web_logs:/var/log/apache2
      - composer_cache:/root/.composer
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ultimate_website
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - APP_ENV=local
      - APP_DEBUG=true
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
    networks:
      - ultimate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    container_name: ultimate-website-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ultimate_website
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    networks:
      - ultimate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ultimate_website"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ultimate-website-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ultimate-network

  redis:
    image: redis:7-alpine
    container_name: ultimate-website-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ultimate-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mailpit:
    image: axllent/mailpit:latest
    container_name: ultimate-website-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - ultimate-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  web_logs:
    driver: local
  db_logs:
    driver: local
  composer_cache:
    driver: local

networks:
  ultimate-network:
    driver: bridge
